"""PubScout HTML report generator — produces email-ready digest from scored publications."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import BaseLoader, Environment

from pubscout.core.models import Publication, ScanRun

logger = logging.getLogger(__name__)

# ── Jinja2 Inline Template ───────────────────────────────────────────

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PubScout Daily Digest</title>
  <style>
    .fb-btn { text-decoration:none; font-size:16px; cursor:pointer; opacity:0.5; transition:opacity 0.15s; }
    .fb-btn:hover { opacity:1; }
    .fb-btn.active { opacity:1; }
    .fb-btn.dimmed { opacity:0.2; pointer-events:none; }
    #fb-bar { position:fixed; bottom:0; left:0; right:0; background:#1a1a2e; color:#fff;
              padding:10px 20px; display:none; z-index:9999; font-family:Arial,sans-serif;
              box-shadow:0 -2px 8px rgba(0,0,0,0.2); }
    #fb-bar span { font-size:14px; }
    #fb-bar button { background:#27ae60; color:#fff; border:none; padding:8px 18px;
                     border-radius:6px; cursor:pointer; font-size:13px; font-weight:700; margin-left:12px; }
    #fb-bar button:hover { background:#219a52; }
  </style>
</head>
<body style="margin:0;padding:0 0 50px;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:700px;margin:0 auto;background:#ffffff;">

    <!-- Header -->
    <div style="background:#1a1a2e;color:#ffffff;padding:24px 28px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:700;">
        PubScout Daily Digest &mdash; {{ date }}
      </h1>
      <p style="margin:0;font-size:13px;color:#b0b0c0;">
        {{ scan_run.sources_checked }} sources checked &middot;
        {{ scan_run.items_fetched }} items found &middot;
        {{ scan_run.items_reported }} reported
      </p>
    </div>

    <!-- Publications -->
    <div style="padding:16px 28px;">
    {% for pub in publications %}
      <div style="border:1px solid #e0e0e0;border-radius:8px;padding:18px 20px;margin-bottom:16px;">
        <!-- Title -->
        <a href="{{ pub.url }}" style="font-size:16px;font-weight:700;color:#1a1a2e;text-decoration:none;">
          {{ pub.title }}
        </a>

        <!-- Authors -->
        <p style="margin:6px 0 4px;font-size:13px;color:#555;">
          {{ format_authors(pub.authors) }}
        </p>

        <!-- Abstract snippet -->
        <p style="margin:6px 0 10px;font-size:13px;color:#333;line-height:1.45;">
          {{ truncate_abstract(pub.abstract) }}
        </p>

        <!-- Meta row: score badge, source, date, domains, feedback -->
        <div style="display:flex;flex-wrap:wrap;align-items:center;gap:8px;font-size:12px;">
          <!-- Score badge -->
          <span style="display:inline-block;padding:2px 10px;border-radius:12px;color:#fff;font-weight:700;background:{{ score_color(pub.relevance_score) }};">
            {{ pub.relevance_score }}
          </span>

          <!-- Source -->
          <span style="color:#777;">{{ pub.source_label }}</span>

          {% if pub.publication_date %}
          <span style="color:#999;">&middot; {{ pub.publication_date.strftime('%Y-%m-%d') }}</span>
          {% endif %}

          {% for domain in pub.matched_domains %}
          <span style="display:inline-block;padding:2px 8px;border-radius:10px;background:#e8e8ec;color:#555;font-size:11px;">
            {{ domain }}
          </span>
          {% endfor %}

          <!-- Feedback buttons (local, no server needed) -->
          <span style="margin-left:auto;" id="fb-{{ pub.id }}">
            <a href="#" class="fb-btn" onclick="return vote('{{ pub.id }}','positive',this)"
               title="Relevant">\U0001f44d</a>
            <a href="#" class="fb-btn" onclick="return vote('{{ pub.id }}','negative',this)"
               style="margin-left:4px;" title="Not relevant">\U0001f44e</a>
          </span>
        </div>
      </div>
    {% endfor %}
    </div>

    <!-- Footer -->
    <div style="background:#f4f4f7;padding:16px 28px;text-align:center;font-size:11px;color:#999;">
      <p style="margin:0 0 6px;">Generated by PubScout | {{ generated_at }}</p>
      <p style="margin:0;font-size:10px;color:#bbb;">
        Click \U0001f44d / \U0001f44e to rate &mdash; feedback saves to database automatically via pubscout:// protocol.
        <br/>Not working? Run <code>pubscout protocol register</code> or use <code>pubscout serve</code> as fallback.
      </p>
    </div>
  </div>

  <!-- Floating feedback bar -->
  <div id="fb-bar">
    <span id="fb-count">0 ratings</span>
    <span id="fb-status" style="font-size:12px;margin-left:12px;color:#27ae60;">Ratings save to database via pubscout:// protocol</span>
    <button onclick="saveFeedback()" id="fb-save-btn" style="display:none;">Save feedback.json</button>
  </div>

  <!-- Feedback handler — uses pubscout:// protocol for instant DB writes -->
  <script>
  var feedback = {};  // { pubId: "positive"|"negative" }
  var stored = localStorage.getItem("pubscout_feedback_{{ date }}");
  if (stored) { try { feedback = JSON.parse(stored); restoreState(); } catch(e) {} }

  function vote(pubId, signal, el) {
    var span = el.parentElement;
    var btns = span.querySelectorAll(".fb-btn");
    // Toggle: if already voted this way, remove
    if (feedback[pubId] === signal) {
      delete feedback[pubId];
      btns.forEach(function(b) { b.className = "fb-btn"; });
    } else {
      feedback[pubId] = signal;
      btns.forEach(function(b) {
        var s = b.getAttribute("onclick").indexOf("positive") > -1 ? "positive" : "negative";
        b.className = s === signal ? "fb-btn active" : "fb-btn dimmed";
      });
      // Fire protocol handler — OS dispatches to pubscout CLI
      var protocolUrl = "pubscout://feedback?id=" + encodeURIComponent(pubId) + "&signal=" + signal;
      var iframe = document.createElement("iframe");
      iframe.style.display = "none";
      iframe.src = protocolUrl;
      document.body.appendChild(iframe);
      setTimeout(function() { document.body.removeChild(iframe); }, 2000);
    }
    persist();
    return false;
  }

  function persist() {
    localStorage.setItem("pubscout_feedback_{{ date }}", JSON.stringify(feedback));
    var n = Object.keys(feedback).length;
    var bar = document.getElementById("fb-bar");
    var cnt = document.getElementById("fb-count");
    bar.style.display = n > 0 ? "flex" : "none";
    bar.style.alignItems = "center";
    bar.style.justifyContent = "center";
    var pos = 0, neg = 0;
    for (var k in feedback) { feedback[k]==="positive" ? pos++ : neg++; }
    cnt.textContent = pos + " \\U0001f44d  " + neg + " \\U0001f44e";
  }

  function restoreState() {
    for (var pubId in feedback) {
      var span = document.getElementById("fb-" + pubId);
      if (!span) continue;
      var signal = feedback[pubId];
      var btns = span.querySelectorAll(".fb-btn");
      btns.forEach(function(b) {
        var s = b.getAttribute("onclick").indexOf("positive") > -1 ? "positive" : "negative";
        b.className = s === signal ? "fb-btn active" : "fb-btn dimmed";
      });
    }
    persist();
  }

  function saveFeedback() {
    var entries = [];
    for (var pubId in feedback) {
      entries.push({ publication_id: pubId, signal: feedback[pubId],
                     timestamp: new Date().toISOString() });
    }
    var blob = new Blob([JSON.stringify(entries, null, 2)], {type: "application/json"});
    var a = document.createElement("a");
    a.href = URL.createObjectURL(blob);
    a.download = "feedback.json";
    a.click();
    URL.revokeObjectURL(a.href);
  }
  </script>
</body>
</html>
"""

EMPTY_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>PubScout — No Results</title></head>
<body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:700px;margin:0 auto;background:#ffffff;padding:28px;">
    <h2 style="color:#1a1a2e;">PubScout Daily Digest</h2>
    <p>Scanned {{ scan_run.sources_checked }} sources, \
found {{ scan_run.items_fetched }} items, \
none met the relevance threshold. \
Consider adjusting your keywords or lowering the threshold.</p>
    <p style="font-size:11px;color:#999;">Generated by PubScout | {{ generated_at }}</p>
  </div>
</body>
</html>
"""


# ── Helper Functions ─────────────────────────────────────────────────

def _score_color(score: float | None) -> str:
    """Return CSS colour for relevance-score badge."""
    if score is None:
        return "#aaa"
    if score >= 8:
        return "#27ae60"  # green
    if score >= 5:
        return "#f39c12"  # yellow / amber
    return "#e74c3c"  # red


def _format_authors(authors: list[str], limit: int = 3) -> str:
    """Show up to *limit* authors, then '+ N more'."""
    if len(authors) <= limit:
        return ", ".join(authors)
    shown = ", ".join(authors[:limit])
    remaining = len(authors) - limit
    return f"{shown} + {remaining} more"


def _truncate_abstract(text: str, max_len: int = 200) -> str:
    """Truncate to *max_len* characters, appending '...' if trimmed."""
    if len(text) <= max_len:
        return text
    return text[:max_len] + "..."


# ── Report Generator ─────────────────────────────────────────────────


class ReportGenerator:
    """Produces HTML email digests from scored publications."""

    def __init__(self) -> None:
        self._env = Environment(loader=BaseLoader(), autoescape=True)
        self._env.globals.update(
            score_color=_score_color,
            format_authors=_format_authors,
            truncate_abstract=_truncate_abstract,
        )

    # ── Public API ───────────────────────────────────────────────────

    def generate_html(self, publications: list[Publication], scan_run: ScanRun) -> str:
        """Generate HTML email digest from scored publications.

        Publications should already be sorted by relevance_score descending.
        """
        template = self._env.from_string(TEMPLATE)
        now = datetime.now(timezone.utc)
        html = template.render(
            publications=publications,
            scan_run=scan_run,
            date=now.strftime("%Y-%m-%d"),
            generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        )
        logger.info("Generated HTML report with %d publications", len(publications))
        return html

    def save_report(self, html: str, output_dir: Path | None = None) -> Path:
        """Save HTML to file. Default: ``~/.pubscout/reports/report_YYYY-MM-DD.html``."""
        if output_dir is None:
            output_dir = Path.home() / ".pubscout" / "reports"
        output_dir.mkdir(parents=True, exist_ok=True)

        filename = f"report_{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.html"
        path = output_dir / filename
        path.write_text(html, encoding="utf-8")
        logger.info("Report saved to %s", path)
        return path

    def generate_empty_summary(self, scan_run: ScanRun) -> str:
        """Generate brief HTML when no publications met threshold."""
        template = self._env.from_string(EMPTY_TEMPLATE)
        now = datetime.now(timezone.utc)
        return template.render(
            scan_run=scan_run,
            generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        )
