"""PubScout HTML report generator — produces email-ready digest from scored publications."""

from __future__ import annotations

import logging
from datetime import datetime, timezone
from pathlib import Path

from jinja2 import BaseLoader, Environment

from pubscout.core.models import Publication, ScanRun

logger = logging.getLogger(__name__)

# ── Jinja2 Inline Template ───────────────────────────────────────────

TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>PubScout Daily Digest</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:700px;margin:0 auto;background:#ffffff;">

    <!-- Header -->
    <div style="background:#1a1a2e;color:#ffffff;padding:24px 28px;">
      <h1 style="margin:0 0 8px;font-size:22px;font-weight:700;">
        PubScout Daily Digest &mdash; {{ date }}
      </h1>
      <p style="margin:0;font-size:13px;color:#b0b0c0;">
        {{ scan_run.sources_checked }} sources checked &middot;
        {{ scan_run.items_fetched }} items found &middot;
        {{ scan_run.items_reported }} reported
      </p>
    </div>

    <!-- Publications -->
    <div style="padding:16px 28px;">
    {% for pub in publications %}
      <div style="border:1px solid #e0e0e0;border-radius:8px;padding:18px 20px;margin-bottom:16px;">
        <!-- Title -->
        <a href="{{ pub.url }}" style="font-size:16px;font-weight:700;color:#1a1a2e;text-decoration:none;">
          {{ pub.title }}
        </a>

        <!-- Authors -->
        <p style="margin:6px 0 4px;font-size:13px;color:#555;">
          {{ format_authors(pub.authors) }}
        </p>

        <!-- Abstract snippet -->
        <p style="margin:6px 0 10px;font-size:13px;color:#333;line-height:1.45;">
          {{ truncate_abstract(pub.abstract) }}
        </p>

        <!-- Meta row: score badge, source, date, domains, feedback -->
        <div style="display:flex;flex-wrap:wrap;align-items:center;gap:8px;font-size:12px;">
          <!-- Score badge -->
          <span style="display:inline-block;padding:2px 10px;border-radius:12px;color:#fff;font-weight:700;background:{{ score_color(pub.relevance_score) }};">
            {{ pub.relevance_score }}
          </span>

          <!-- Source -->
          <span style="color:#777;">{{ pub.source_label }}</span>

          {% if pub.publication_date %}
          <span style="color:#999;">&middot; {{ pub.publication_date.strftime('%Y-%m-%d') }}</span>
          {% endif %}

          {% for domain in pub.matched_domains %}
          <span style="display:inline-block;padding:2px 8px;border-radius:10px;background:#e8e8ec;color:#555;font-size:11px;">
            {{ domain }}
          </span>
          {% endfor %}

          <!-- Feedback links -->
          <span style="margin-left:auto;" class="fb-links">
            <a href="#" data-pub-id="{{ pub.id }}" data-signal="positive"
               onclick="return sendFeedback(this)" style="text-decoration:none;font-size:16px;cursor:pointer;" title="Relevant">\U0001f44d</a>
            <a href="#" data-pub-id="{{ pub.id }}" data-signal="negative"
               onclick="return sendFeedback(this)" style="text-decoration:none;font-size:16px;margin-left:4px;cursor:pointer;" title="Not relevant">\U0001f44e</a>
          </span>
        </div>
      </div>
    {% endfor %}
    </div>

    <!-- Footer -->
    <div style="background:#f4f4f7;padding:16px 28px;text-align:center;font-size:11px;color:#999;">
      <p style="margin:0 0 6px;">Generated by PubScout | {{ generated_at }}</p>
      <p style="margin:0;font-size:10px;color:#bbb;">
        Feedback links require the server: <code>pubscout feedback serve</code>
      </p>
    </div>
  </div>

  <!-- Feedback handler — degrades gracefully in email clients (JS stripped) -->
  <script>
  var FB_BASE = "{{ feedback_base_url }}";
  function sendFeedback(el) {
    var pubId = el.getAttribute("data-pub-id");
    var signal = el.getAttribute("data-signal");
    var url = FB_BASE + "/feedback?id=" + encodeURIComponent(pubId) + "&signal=" + signal;
    var span = el.parentElement;

    fetch(url).then(function(r) {
      if (r.ok) {
        span.innerHTML = '<span style="color:#27ae60;font-size:13px;font-weight:700;">' +
          (signal === 'positive' ? '\U0001f44d' : '\U0001f44e') + ' Recorded</span>';
      } else {
        r.text().then(function(t) { showFbError(span, t); });
      }
    }).catch(function() {
      showFbError(span,
        'Feedback server not running.\\nStart it with: pubscout feedback serve');
    });
    return false;
  }
  function showFbError(span, msg) {
    span.innerHTML = '<span style="color:#e74c3c;font-size:11px;" title="' +
      msg.replace(/"/g,'&quot;') + '">\u26a0\ufe0f Server offline</span>';
  }
  </script>
</body>
</html>
"""

EMPTY_TEMPLATE = """\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><title>PubScout — No Results</title></head>
<body style="margin:0;padding:0;background:#f4f4f7;font-family:Arial,Helvetica,sans-serif;">
  <div style="max-width:700px;margin:0 auto;background:#ffffff;padding:28px;">
    <h2 style="color:#1a1a2e;">PubScout Daily Digest</h2>
    <p>Scanned {{ scan_run.sources_checked }} sources, \
found {{ scan_run.items_fetched }} items, \
none met the relevance threshold. \
Consider adjusting your keywords or lowering the threshold.</p>
    <p style="font-size:11px;color:#999;">Generated by PubScout | {{ generated_at }}</p>
  </div>
</body>
</html>
"""


# ── Helper Functions ─────────────────────────────────────────────────

def _score_color(score: float | None) -> str:
    """Return CSS colour for relevance-score badge."""
    if score is None:
        return "#aaa"
    if score >= 8:
        return "#27ae60"  # green
    if score >= 5:
        return "#f39c12"  # yellow / amber
    return "#e74c3c"  # red


def _format_authors(authors: list[str], limit: int = 3) -> str:
    """Show up to *limit* authors, then '+ N more'."""
    if len(authors) <= limit:
        return ", ".join(authors)
    shown = ", ".join(authors[:limit])
    remaining = len(authors) - limit
    return f"{shown} + {remaining} more"


def _truncate_abstract(text: str, max_len: int = 200) -> str:
    """Truncate to *max_len* characters, appending '...' if trimmed."""
    if len(text) <= max_len:
        return text
    return text[:max_len] + "..."


# ── Report Generator ─────────────────────────────────────────────────


class ReportGenerator:
    """Produces HTML email digests from scored publications."""

    def __init__(self, feedback_base_url: str = "http://localhost:8230") -> None:
        self.feedback_base_url = feedback_base_url.rstrip("/")
        self._env = Environment(loader=BaseLoader(), autoescape=True)
        self._env.globals.update(
            score_color=_score_color,
            format_authors=_format_authors,
            truncate_abstract=_truncate_abstract,
        )

    # ── Public API ───────────────────────────────────────────────────

    def generate_html(self, publications: list[Publication], scan_run: ScanRun) -> str:
        """Generate HTML email digest from scored publications.

        Publications should already be sorted by relevance_score descending.
        """
        template = self._env.from_string(TEMPLATE)
        now = datetime.now(timezone.utc)
        html = template.render(
            publications=publications,
            scan_run=scan_run,
            date=now.strftime("%Y-%m-%d"),
            generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
            feedback_base_url=self.feedback_base_url,
        )
        logger.info("Generated HTML report with %d publications", len(publications))
        return html

    def save_report(self, html: str, output_dir: Path | None = None) -> Path:
        """Save HTML to file. Default: ``~/.pubscout/reports/report_YYYY-MM-DD.html``."""
        if output_dir is None:
            output_dir = Path.home() / ".pubscout" / "reports"
        output_dir.mkdir(parents=True, exist_ok=True)

        filename = f"report_{datetime.now(timezone.utc).strftime('%Y-%m-%d')}.html"
        path = output_dir / filename
        path.write_text(html, encoding="utf-8")
        logger.info("Report saved to %s", path)
        return path

    def generate_empty_summary(self, scan_run: ScanRun) -> str:
        """Generate brief HTML when no publications met threshold."""
        template = self._env.from_string(EMPTY_TEMPLATE)
        now = datetime.now(timezone.utc)
        return template.render(
            scan_run=scan_run,
            generated_at=now.strftime("%Y-%m-%d %H:%M UTC"),
        )
